### ISSUE TITLE
RFE: ldaps 

### ISSUE THREAD

**Issue by ohauer** [raffaelespazzoli/orgs-management-ocp#2]
First thanks for your summary and article https://www.openshift.com/blog/orgs-management-and-team-onboarding-in-openshift-a-fully-automated-approach

Since most LDAP system running ldaps today I'm missing the hint how to integrate the ca-bundle for ldaps/Acive Direcory using a self sign CA with the keycloak operator.
It's easy to setup keycloak on docker or without the operator on k8s and add the ca-bundle, perhaps you can extend your sample with an ldaps configuration.

**Comment by raffaelespazzoli** [comment]
assuming you know how to configure the keycloak ldap connector with a cabundle, then the simplest way to get the cabundle in a pod is to create a secret and mount it in the pod. I am not sure if this is supported by the RH-SSO operator. If not, maybe you could file an RFE to that project.

**Comment by ohauer** [comment]
Thanks, meanwhile we build the keycloak outside from openshift
